### PR TITLE
Specifying goals and possible additions.

### PR DESCRIPTION
**Pull request by JoeCrawford99**

### CODE REVIEW

**Review by JoshSE2019 — APPROVED** [review]
I like the addition of the end date and the possible use of the database.

**Review by princeproject911 — APPROVED** [review]
These are useful additions.

**Review by Sdam627 — COMMENTED** [review]
These revisions look good to me.

**Review by Sdam627 — APPROVED** [review]
These revisions look good to me!

**Review by ash4747 — APPROVED** [review]
good  , i love python

**Pull request merged**
